version: '3.4'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  slipka: 
    image: bashamer/slipka
    depends_on: 
      - db
    links: 
      - "db:db"
    ports:
      - "4445:4445"
      - "61710-61920:61710-61920"
  hub:
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
  node-chrome:
    image: selenium/node-chrome
    depends_on: 
      - hub
      - slipka
    links: 
      - "hub:hub"
      - "slipka:slipka"
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443


