// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PossumLabs.DSL.Web.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ScriptBasedClearFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "features", "Script Based Clear", "\tusing javascript driven clear on \'//div[@id=\"sandbox-container\"]/input\'", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Script Based Clear.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("datepicker external enter and clear")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Script Based Clear")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Text input", "11/11/2000", "//div[@id=\"sandbox-container\"]/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Component", "11/11/2000", "//*[@id=\"sandbox-container\"]/div/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Text input autoclose", "11/11/2000", "//div[@id=\"sandbox-container\"]/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&autoclose=on&keyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Component autoclose", "11/11/2000", "//*[@id=\"sandbox-container\"]/div/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&autoclose=on&KeyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Text input no forceparse", "11/11/2000", "//div[@id=\"sandbox-container\"]/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Component no forceparse", "11/11/2000", "//*[@id=\"sandbox-container\"]/div/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&KeyboardNavigation=on#sandbox", null)]
        public async global::System.Threading.Tasks.Task DatepickerExternalEnterAndClear(string name, string entry, string xpath, string url, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("entry", entry);
            argumentsOfScenario.Add("xpath", xpath);
            argumentsOfScenario.Add("url", url);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("datepicker external enter and clear", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
 await testRunner.GivenAsync(string.Format("navigated to \'{0}\'", url), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
 await testRunner.WhenAsync(string.Format("entering \'{0}\' into element \'//div[@id=\"sandbox-container\"]/input\'", entry), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
 await testRunner.AndAsync("clicking the element \'#sandbox-html\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
 await testRunner.AndAsync("using javascript driven clear on \'//div[@id=\"sandbox-container\"]/input\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
 await testRunner.AndAsync("clicking the element \'#sandbox-html\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.ThenAsync("the element \'//div[@id=\"sandbox-container\"]/input\' has the value \'\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("datepicker external enter and clear version 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Script Based Clear")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Text input", "11/11/2000", "//div[@id=\"sandbox-container\"]/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Component", "11/11/2000", "//*[@id=\"sandbox-container\"]/div/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Text input autoclose", "11/11/2000", "//div[@id=\"sandbox-container\"]/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&autoclose=on&KeyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Component autoclose", "11/11/2000", "//*[@id=\"sandbox-container\"]/div/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&autoclose=on&KeyboardNavigation=on&forceParse=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Text input no forceparse", "11/11/2000", "//div[@id=\"sandbox-container\"]/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&KeyboardNavigation=on#sandbox", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Component no forceparse", "11/11/2000", "//*[@id=\"sandbox-container\"]/div/input", @"https://uxsolutions.github.io/bootstrap-datepicker/?markup=component&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&KeyboardNavigation=on#sandbox", null)]
        public async global::System.Threading.Tasks.Task DatepickerExternalEnterAndClearVersion2(string name, string entry, string xpath, string url, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("entry", entry);
            argumentsOfScenario.Add("xpath", xpath);
            argumentsOfScenario.Add("url", url);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("datepicker external enter and clear version 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
 await testRunner.GivenAsync(string.Format("navigated to \'{0}\'", url), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
 await testRunner.WhenAsync("clicking the element \'Switch to Bootstrap 2\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
 await testRunner.AndAsync(string.Format("entering \'{0}\' into element \'//div[@id=\"sandbox-container\"]/input\'", entry), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.AndAsync("clicking the element \'#sandbox-html\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("using javascript driven clear on \'//div[@id=\"sandbox-container\"]/input\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("clicking the element \'#sandbox-html\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.ThenAsync("the element \'//div[@id=\"sandbox-container\"]/input\' has the value \'\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("external enter and clear")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Script Based Clear")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Date", "#date", "11112000", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Date             zero padded", "#date", "01012000", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Hour", "#time", "111111", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Date & Hour", "#date_time", "11112000111111", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("ZIP Code", "#cep", "80202", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("With Callbacks (open console)", "#cep_with_callback", "80202", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Crazy Zip Code", "#crazy_cep", "8020211", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Money", "#money", "123456", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Telephone", "#phone", "1234567", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Telephone with Code Area", "#phone_with_ddd", "1234567890", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("US Telephone", "#phone_us", "1234567890", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("São Paulo Celphones", "#sp_celphones", "1234567890", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Mixed Type Mask", "#mixed", "123456a", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("CPF", "#cpf", "1234567890", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("CNPJ", "#cnpj", "1234567890", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("IP Address", "#ip_address", "123123123123", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("With Clear If Not Match Option", "#clear-if-not-match", "01012000", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("With a fallback digit", "#fallback", "01012000", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("With selectOnFocus", "#selectonfocus", "01012000", null)]
        public async global::System.Threading.Tasks.Task ExternalEnterAndClear(string name, string id, string entry, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("id", id);
            argumentsOfScenario.Add("entry", entry);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("external enter and clear", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
 await testRunner.GivenAsync("navigated to \'https://igorescobar.github.io/jQuery-Mask-Plugin/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
 await testRunner.WhenAsync(string.Format("entering \'{0}\' into element \'{1}\'", entry, id), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
 await testRunner.WhenAsync(string.Format("using javascript driven clear on \'{0}\'", id), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
 await testRunner.ThenAsync(string.Format("the element \'{0}\' has the value \'\'", id), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
