// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace PossumLabs.DSL.Slipka.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TaggingCallsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "Slipka"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Tagging Calls", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "Tagging.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
            global::Reqnroll.Table table103 = new global::Reqnroll.Table(new string[] {
                        "var",
                        "Destination"});
            table103.AddRow(new string[] {
                        "P1",
                        "http://PossumLabs.com"});
#line 5
 await testRunner.GivenAsync("the Slipka Proxy", ((string)(null)), table103, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Tagging happy path")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Tagging Calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Slipka")]
        public async global::System.Threading.Tasks.Task TaggingHappyPath()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tagging happy path", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table104 = new global::Reqnroll.Table(new string[] {
                            "Uri",
                            "Response Content",
                            "StatusCode",
                            "Method"});
                table104.AddRow(new string[] {
                            "test",
                            "Hello World",
                            "200",
                            "GET"});
                table104.AddRow(new string[] {
                            "other",
                            "Hello World",
                            "200",
                            "GET"});
#line 10
 await testRunner.GivenAsync("the Proxy \'P1\' injects the calls", ((string)(null)), table104, "Given ");
#line hidden
                global::Reqnroll.Table table105 = new global::Reqnroll.Table(new string[] {
                            "Uri",
                            "Tags"});
                table105.AddRow(new string[] {
                            "test",
                            "[\'Test\']"});
#line 14
 await testRunner.GivenAsync("the Proxy \'P1\' tags the calls", ((string)(null)), table105, "Given ");
#line hidden
                global::Reqnroll.Table table106 = new global::Reqnroll.Table(new string[] {
                            "var",
                            "Host",
                            "Path",
                            "Method"});
                table106.AddRow(new string[] {
                            "C1",
                            "P1.ProxyUri",
                            "test",
                            "GET"});
                table106.AddRow(new string[] {
                            "C2",
                            "P1.ProxyUri",
                            "other",
                            "GET"});
#line 17
 await testRunner.AndAsync("the Call", ((string)(null)), table106, "And ");
#line hidden
#line 21
 await testRunner.WhenAsync("the Call \'C1\' is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
 await testRunner.AndAsync("the Call \'C2\' is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("wait 1000 ms", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.ThenAsync("retrieving the tagged calls from Proxy \'P1\' with tag \'Test\' as \'RC\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table107 = new global::Reqnroll.Table(new string[] {
                            "Count"});
                table107.AddRow(new string[] {
                            "1"});
#line 25
 await testRunner.AndAsync("\'RC\' has the values", ((string)(null)), table107, "And ");
#line hidden
                global::Reqnroll.Table table108 = new global::Reqnroll.Table(new string[] {
                            "Path",
                            "StatusCode",
                            "Tags"});
                table108.AddRow(new string[] {
                            "/test",
                            "200",
                            "[\'Test\']"});
#line 28
 await testRunner.AndAsync("\'RC[0]\' has the values", ((string)(null)), table108, "And ");
#line hidden
#line 31
 await testRunner.AndAsync("retrieving the Session from Proxy \'P1\' as \'S1\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table109 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table109.AddRow(new string[] {
                            "[\'Test\']"});
#line 32
 await testRunner.AndAsync("\'S1\' has the values", ((string)(null)), table109, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Tagging slow calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Tagging Calls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Slipka")]
        public async global::System.Threading.Tasks.Task TaggingSlowCalls()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tagging slow calls", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table110 = new global::Reqnroll.Table(new string[] {
                            "Uri",
                            "Response Content",
                            "StatusCode",
                            "Method",
                            "Duration"});
                table110.AddRow(new string[] {
                            "fast",
                            "Hello World",
                            "200",
                            "GET",
                            "1"});
                table110.AddRow(new string[] {
                            "slow",
                            "Hello World",
                            "200",
                            "GET",
                            "4000"});
#line 38
 await testRunner.GivenAsync("the Proxy \'P1\' injects the calls", ((string)(null)), table110, "Given ");
#line hidden
                global::Reqnroll.Table table111 = new global::Reqnroll.Table(new string[] {
                            "var",
                            "Destination"});
                table111.AddRow(new string[] {
                            "P2",
                            "P1.ProxyUri"});
#line 42
 await testRunner.GivenAsync("the Slipka Proxy", ((string)(null)), table111, "Given ");
#line hidden
                global::Reqnroll.Table table112 = new global::Reqnroll.Table(new string[] {
                            "Tags",
                            "Method",
                            "Duration"});
                table112.AddRow(new string[] {
                            "[\'Test\']",
                            "GET",
                            "3000"});
#line 45
 await testRunner.GivenAsync("the Proxy \'P2\' tags the calls", ((string)(null)), table112, "Given ");
#line hidden
                global::Reqnroll.Table table113 = new global::Reqnroll.Table(new string[] {
                            "var",
                            "Host",
                            "Path",
                            "Method"});
                table113.AddRow(new string[] {
                            "C1",
                            "P2.ProxyUri",
                            "fast",
                            "GET"});
                table113.AddRow(new string[] {
                            "C2",
                            "P2.ProxyUri",
                            "slow",
                            "GET"});
#line 48
 await testRunner.AndAsync("the Call", ((string)(null)), table113, "And ");
#line hidden
#line 52
 await testRunner.WhenAsync("the Call \'C1\' is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
 await testRunner.AndAsync("the Call \'C2\' is executed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
 await testRunner.AndAsync("wait 1000 ms", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.ThenAsync("retrieving the tagged calls from Proxy \'P2\' with tag \'Test\' as \'RC\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table114 = new global::Reqnroll.Table(new string[] {
                            "Count"});
                table114.AddRow(new string[] {
                            "1"});
#line 56
 await testRunner.AndAsync("\'RC\' has the values", ((string)(null)), table114, "And ");
#line hidden
                global::Reqnroll.Table table115 = new global::Reqnroll.Table(new string[] {
                            "Path",
                            "StatusCode",
                            "Tags"});
                table115.AddRow(new string[] {
                            "/slow",
                            "200",
                            "[\'Test\']"});
#line 59
 await testRunner.AndAsync("\'RC[0]\' has the values", ((string)(null)), table115, "And ");
#line hidden
#line 62
 await testRunner.AndAsync("retrieving the Session from Proxy \'P2\' as \'S2\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table116 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table116.AddRow(new string[] {
                            "[\'Test\']"});
#line 63
 await testRunner.AndAsync("\'S2\' has the values", ((string)(null)), table116, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
