version: '3.4'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  slipka: 
    image: bashamer/slipka
    depends_on: 
      - db
    links: 
      - "db:db"
    ports:
      - "4445:4445"
      - "61710-61920:61710-61920"
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      TZ: US/Mountain
  
  node-chrome:
    image: selenium/node-chrome
    depends_on: 
      - hub
      - slipka
    links: 
      - "hub:hub"
      - "slipka:slipka"
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      TZ: US/Mountain
    deploy:
      mode: replicated
      replicas: 6
